cache:
  directories:
    - .build/checkouts
    - .build/repositories
os: osx
language: objective-c
osx_image: xcode11
install: executable/init
script:
  - swift build
  - summon/bin tuist generate
  - xcodebuild build -workspace SteroidUIKit.xcworkspace -scheme SteroidUIKit -sdk iphonesimulator
deploy:
  provider: script
  script: summon/bin pod trunk push
  on:
    tags: true
